// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCjProductOperation = "cj_product_operation"

// CjProductOperation 产品操作
type CjProductOperation struct {
	ID           uint32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ProductID    uint32    `gorm:"column:product_id;type:int unsigned;not null;index:PRODUCT_INDEX,priority:1;comment:产品ID" json:"product_id"`                                                         // 产品ID
	OperatorID   uint32    `gorm:"column:operator_id;type:int unsigned;not null;index:OPERATOR_INDEX,priority:1;comment:操作者ID" json:"operator_id"`                                                     // 操作者ID
	OperatorName string    `gorm:"column:operator_name;type:varchar(30);not null;comment:操作者名" json:"operator_name"`                                                                                   // 操作者名
	OperateAt    time.Time `gorm:"column:operate_at;type:datetime;not null;comment:操作时间" json:"operate_at"`                                                                                            // 操作时间
	OperateType  uint32    `gorm:"column:operate_type;type:tinyint unsigned;not null;index:OPERATOR_INDEX,priority:2;index:PRODUCT_INDEX,priority:2;comment:操作类型 1.增 2.删 3.改 4.复" json:"operate_type"` // 操作类型 1.增 2.删 3.改 4.复
}

// TableName CjProductOperation's table name
func (*CjProductOperation) TableName() string {
	return TableNameCjProductOperation
}
