@host = http://127.0.0.1:12345

###
# @name captcha
GET {{host}}/captcha/math HTTP/1.1


###
# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin",
    "captchaId":  "{{captcha.response.body.$.data.id}}",
    "captchaAnswer": "-11"
}