@host = http://127.0.0.1:12345


###
# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
# @name producAdd
PUT {{host}}/api/product/add HTTP/1.1
Content-Type: application/json
Authorization: {{login.response.body.$.data}}

{
    "number": "2033993",
    "fullname": "名字AAAA22",
    "shortname": "AA33"
}

###
# @name productDetial
GET {{host}}/api/product/detail?id=4 HTTP/1.1
Authorization: {{login.response.body.$.data}}

###
# @name productEdit
POST {{host}}/api/product/edit HTTP/1.1
Content-Type: application/json
Authorization: {{login.response.body.$.data}}

{
    "id": 12,
    "number": "2020",
    "fullname": "名字AAAA565612",
    "shortname": "AA"
}