// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCjEmployee = "cj_employee"

// CjEmployee mapped from table <cj_employee>
type CjEmployee struct {
	ID       *int32  `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Username string  `gorm:"column:username;type:STRING;not null" json:"username"`
	Password *string `gorm:"column:password;type:STRING" json:"password"`
	Nickname *string `gorm:"column:nickname;type:STRING" json:"nickname"`
}

// TableName CjEmployee's table name
func (*CjEmployee) TableName() string {
	return TableNameCjEmployee
}
