// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCjEmployeePermission = "cj_employee_permission"

// CjEmployeePermission mapped from table <cj_employee_permission>
type CjEmployeePermission struct {
	ID           *int32 `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	EmployeeID   *int32 `gorm:"column:employee_id;type:INTEGER" json:"employee_id"`
	PermissionID *int32 `gorm:"column:permission_id;type:INTEGER" json:"permission_id"`
}

// TableName CjEmployeePermission's table name
func (*CjEmployeePermission) TableName() string {
	return TableNameCjEmployeePermission
}
