// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCjOperation = "cj_operation"

// CjOperation mapped from table <cj_operation>
type CjOperation struct {
	ID             int32     `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	OperatorID     int32     `gorm:"column:operator_id;type:INTEGER;not null" json:"operator_id"`
	OperateAt      time.Time `gorm:"column:operate_at;type:DATETIME;not null" json:"operate_at"`
	OperateSummary string    `gorm:"column:operate_summary;type:text;not null" json:"operate_summary"`
}

// TableName CjOperation's table name
func (*CjOperation) TableName() string {
	return TableNameCjOperation
}
